import os
import sys
import numpy as np
import pandas as pd

TARGET_COLUMN="Result"
PIPELINE_NAME="NetworkSecurity"
ARTIFACT_DIR="artifacts"
FILE_NAME="phisingData.csv"
TRAIN_FILE_NAME="train.csv"
TEST_FILE_NAME="test.csv"
DATA_INGESTION_COLLECTION_NAME="NetworkData" # NAME SAME AS MONGODB ATLAS
DATA_INGESTION_DATABASE_NAME="ABHINAVANAND" # NAME SAME AS MONGODB ATLAS
DATA_INGESTION_DIR_NAME="data_ingestion"
DATA_INGESTION_FEATURE_STORE_DIR_NAME="featurestore"
DATA_INGESTION_INGESTED_DIR_NAME="ingested"
DATA_INGESTION_TRAIN_TEST_SPLIT_RATIO=0.2
