import os
import sys
import numpy as np
import pandas as pd

TARGET_COLUMN="Result"
PIPELINE_NAME="NetworkSecurity"
ARTIFACT_DIR="artifacts"
FILE_NAME="phisingData.csv"

TRAIN_FILE_NAME="train.csv"
TEST_FILE_NAME="test.csv"
PREPROCESSOR_FILE_NAME="preprocessor.pkl"

SCHEMA_FILE_PATH=os.path.join("data_schema","schema.yaml")


DATA_INGESTION_COLLECTION_NAME="NetworkData" # NAME SAME AS MONGODB ATLAS
DATA_INGESTION_DATABASE_NAME="ABHINAVANAND" # NAME SAME AS MONGODB ATLAS
DATA_INGESTION_DIR_NAME="data_ingestion"
DATA_INGESTION_FEATURE_STORE_DIR_NAME="featurestore"
DATA_INGESTION_INGESTED_DIR_NAME="ingested"
DATA_INGESTION_TRAIN_TEST_SPLIT_RATIO=0.2

DATA_VALIDATION_DIR_NAME="data_validation"
DATA_VALIDATION_VALID_DIR="valid"
DATA_VALIDATION_INVALID_DIR="invalid"
DATA_VALIDATION_DRIFT_REPORT_DIR="drift_report"
DATA_VALIDATION_DRIFT_REPORT_FILE_NAME="report.yaml"

DATA_TRANFORMATION_DIR_NAME="data_transformation"
DATA_TRANSFORMATION_TRANSFORMED_DIR="transformed"
DATA_TRANSOFORMATION_PREPROCESSOR_DIR="preprocessor"
DATA_TRANSFORMATION_IMPUTER_PARAM:dict={
    "missing_values":np.nan,
    "n_neighbors":3,
    "weights":"uniform"
}



